import { EnvConfig } from '../src/types';

export function generateDockerfile(config: EnvConfig): string {
  const envLines = Object.entries(config.envVars ?? {})
    .map(([k, v]) => `ENV ${k}="${v}"`)
    .join('\n');

  return `# Dockerfile — generated by Edge Deployer
# Runs your edge function as a standard HTTP server (Node.js)
FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package*.json ./
RUN npm ci --omit=dev

FROM base AS runner
COPY --from=deps /app/node_modules ./node_modules
COPY . .

${envLines || '# ENV MY_VAR="value"'}

EXPOSE 3000

# Minimal HTTP adapter for the edge function
RUN printf 'const http = require("http");\\n\
const { ReadableStream } = require("stream/web");\\n\
\\n\
require("./index.js");\\n\
\\n\
const server = http.createServer(async (req, res) => {\\n\
  const url = \`http://\${req.headers.host}\${req.url}\`;\\n\
  const request = new Request(url, {\\n\
    method: req.method,\\n\
    headers: Object.fromEntries(Object.entries(req.headers)),\\n\
  });\\n\
  const response = await handleRequest(request);\\n\
  res.writeHead(response.status, Object.fromEntries(response.headers));\\n\
  const text = await response.text();\\n\
  res.end(text);\\n\
});\\n\
server.listen(3000, () => console.log("Edge function running on :3000"));\\n' > server.js

CMD ["node", "server.js"]
`;
}

export function generateKubernetesYAML(config: EnvConfig, imageName: string): string {
  const name = config.cfScriptName ?? config.awsLambdaName ?? 'edge-function';
  const envLines = Object.entries(config.envVars ?? {})
    .map(([k, v]) => `        - name: ${k}\n          value: "${v}"`)
    .join('\n');

  return `# kubernetes.yaml — generated by Edge Deployer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  labels:
    app: ${name}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: ${name}
          image: ${imageName || `${name}:latest`}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
${envLines || '            []'}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}-svc
spec:
  selector:
    app: ${name}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
`;
}
