import { EnvConfig } from '../src/types';

export function generateWrangler(config: EnvConfig): string {
  const vars = Object.entries(config.envVars ?? {})
    .map(([k, v]) => `${k} = "${v}"`)
    .join('\n');

  return `# wrangler.toml — generated by Edge Deployer
name = "${config.cfScriptName ?? 'my-worker'}"
main = "index.js"
compatibility_date = "${new Date().toISOString().split('T')[0]}"

account_id = "${config.cfAccountId ?? ''}"

[vars]
${vars || '# ENV = "production"'}

# Uncomment to enable KV namespace binding
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "<your-kv-namespace-id>"

# Uncomment for R2 bucket
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Uncomment for D1 database
# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = "<your-d1-database-id>"

[build]
command = ""

[dev]
port = 8787
local_protocol = "http"
`;
}
