import { app, BrowserWindow, ipcMain, dialog, shell } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import { bundleAndSave } from './deployer';
import { deployToSelectedCloud, rollbackDeploy, healthcheckDeploy } from './multiCloudDeployer';
import { generatePulumiCloudflare } from './generatePulumiCloudflare';
import { generateTerraform } from './generateTerraform';
import { generateWrangler } from './generateWrangler';
import { generateDockerfile, generateKubernetesYAML } from './generateDockerfile';
import { saveSecret, loadSecrets, deleteSecret } from './secretsVault';
import { askAI, generateWorkerFromPrompt } from './aiAssistant';
import { loadPluginManifests } from './pluginLoader';
import {
  saveWorkspace, openWorkspace, openRecentProject, loadRecentProjects, autoSaveWorkspace,
} from './workspace';
import { importFromCloud, detectDrift } from './cloudImporter';
import { getTelemetryLevel, setTelemetryLevel, recordEvent } from './telemetry';
import { EnvConfig, DeployRecord, AIMessage, SecretEntry, WorkspaceData, TelemetryLevel } from '../src/types';
import dotenv from 'dotenv';

dotenv.config();

let mainWindow: BrowserWindow | null = null;

function log(msg: string) {
  mainWindow?.webContents.send('deploy-log', msg);
}

// ─── Window ───────────────────────────────────────────────────────────────
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1024,
    minHeight: 700,
    backgroundColor: '#121212',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  mainWindow.loadURL('http://localhost:8080');
  mainWindow.on('closed', () => { mainWindow = null; });
}

app.whenReady().then(createWindow);
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
app.on('activate', () => { if (!mainWindow) createWindow(); });

// ─── File operations ──────────────────────────────────────────────────────
ipcMain.handle('save-file', async (_e, code: string) => {
  const { filePath, canceled } = await dialog.showSaveDialog({
    filters: [{ name: 'JavaScript', extensions: ['js'] }, { name: 'TypeScript', extensions: ['ts'] }],
  });
  if (canceled || !filePath) return false;
  fs.writeFileSync(filePath, code, 'utf-8');
  return true;
});

ipcMain.handle('open-file', async () => {
  const { filePaths, canceled } = await dialog.showOpenDialog({
    properties: ['openFile'],
    filters: [
      { name: 'JavaScript / TypeScript', extensions: ['js', 'ts', 'mjs'] },
      { name: 'All Files', extensions: ['*'] },
    ],
  });
  if (canceled || !filePaths.length) return null;
  return fs.readFileSync(filePaths[0], 'utf-8');
});

ipcMain.handle('deploy-code', async (_e, code: string) => {
  return bundleAndSave(code);
});

// ─── Deploy ───────────────────────────────────────────────────────────────
ipcMain.handle('deploy-to-cloud', async (_e, code: string, config: EnvConfig) => {
  log('Starting deployment...');
  try {
    const result = await deployToSelectedCloud(code, config, log);
    log(`✅ Deployed: ${result.url} (${result.latencyMs}ms)`);
    return result;
  } catch (err: any) {
    log(`❌ Deploy failed: ${err.message}`);
    throw err;
  }
});

ipcMain.handle('rollback-deploy', async (_e, record: DeployRecord, config: EnvConfig) => {
  log(`Rolling back to ${record.timestamp}...`);
  try {
    const result = await rollbackDeploy(record, config, log);
    log(`✅ Rollback complete: ${result.url}`);
    return result;
  } catch (err: any) {
    log(`❌ Rollback failed: ${err.message}`);
    throw err;
  }
});

// ─── Legacy handler (keep for backward compat) ────────────────────────────
ipcMain.handle('deploy-to-cloudflare', async (_e, code: string) => {
  log('✅ Starting Cloudflare deployment...');
  const config: EnvConfig = {
    cloudProvider: 'cloudflare',
    cfApiToken: process.env.CF_API_TOKEN,
    cfAccountId: process.env.CF_ACCOUNT_ID,
    cfScriptName: process.env.CF_SCRIPT_NAME,
  };
  const result = await deployToSelectedCloud(code, config, log);
  return result;
});

// ─── IaC exports ──────────────────────────────────────────────────────────
ipcMain.handle('download-pulumi', async (_e, config: EnvConfig, code: string) => {
  const JSZip = require('jszip');
  const pulumiCode = generatePulumiCloudflare(config, code, true);
  const zip = new JSZip();
  zip.file('Pulumi.yaml', `name: edge-deployer-worker\ndescription: Generated by Edge Deployer\nruntime: nodejs`);
  zip.file('index.ts', pulumiCode);
  zip.file('package.json', JSON.stringify({ name: 'pulumi-cloudflare', dependencies: { '@pulumi/cloudflare': 'latest', '@pulumi/pulumi': 'latest' } }, null, 2));

  const content = await zip.generateAsync({ type: 'nodebuffer' });
  const filePath = path.join(app.getPath('downloads'), 'pulumi-cloudflare.zip');
  fs.writeFileSync(filePath, content);
  shell.openPath(path.dirname(filePath));
  return filePath;
});

ipcMain.handle('download-terraform', async (_e, config: EnvConfig, code: string) => {
  const tf = generateTerraform(config, code);
  const dir = path.join(app.getPath('downloads'), `terraform-${config.cloudProvider}`);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'main.tf'), tf);
  fs.writeFileSync(path.join(dir, 'worker.js'), code);
  fs.writeFileSync(path.join(dir, 'variables.tf'), `variable "cloudflare_api_token" { type = string sensitive = true }\nvariable "cloudflare_zone_id" { type = string }\n`);
  shell.openPath(dir);
  return dir;
});

ipcMain.handle('download-wrangler', async (_e, config: EnvConfig, code: string) => {
  const toml = generateWrangler(config);
  const dir = path.join(app.getPath('downloads'), 'wrangler-project');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'wrangler.toml'), toml);
  fs.writeFileSync(path.join(dir, 'index.js'), code);
  shell.openPath(dir);
  return dir;
});

ipcMain.handle('download-dockerfile', async (_e, config: EnvConfig, code: string) => {
  const dockerfile = generateDockerfile(config);
  const k8s = generateKubernetesYAML(config, 'my-edge-function:latest');
  const dir = path.join(app.getPath('downloads'), 'docker-project');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'Dockerfile'), dockerfile);
  fs.writeFileSync(path.join(dir, 'kubernetes.yaml'), k8s);
  fs.writeFileSync(path.join(dir, 'index.js'), code);
  shell.openPath(dir);
  return dir;
});

// ─── Secrets vault ────────────────────────────────────────────────────────
ipcMain.handle('save-secret', async (_e, entry: SecretEntry) => {
  saveSecret(entry);
});

ipcMain.handle('load-secrets', async () => {
  return loadSecrets();
});

ipcMain.handle('delete-secret', async (_e, key: string) => {
  deleteSecret(key);
});

// ─── AI assistant ─────────────────────────────────────────────────────────
ipcMain.handle('ai-assist', async (_e, messages: AIMessage[], code: string, apiKey: string) => {
  return askAI(messages, code, apiKey);
});

// ─── Plugins ──────────────────────────────────────────────────────────────
ipcMain.handle('load-plugins', async () => {
  return loadPluginManifests();
});

// ─── Workspace ────────────────────────────────────────────────────────────
ipcMain.handle('save-workspace', async (_e, data: WorkspaceData) => {
  return saveWorkspace(data);
});

ipcMain.handle('open-workspace', async () => {
  return openWorkspace();
});

ipcMain.handle('load-recent-projects', async () => {
  return loadRecentProjects();
});

ipcMain.handle('open-recent-project', async (_e, filePath: string) => {
  return openRecentProject(filePath);
});

ipcMain.handle('auto-save-workspace', async (_e, filePath: string, data: WorkspaceData) => {
  autoSaveWorkspace(filePath, data);
});

// ─── Cloud import ─────────────────────────────────────────────────────────
ipcMain.handle('import-from-cloud', async (_e, config: EnvConfig) => {
  log(`Importing from ${config.cloudProvider}...`);
  try {
    const result = await importFromCloud(config);
    log(`✅ Imported: ${result.name}`);
    return result;
  } catch (err: any) {
    log(`❌ Import failed: ${err.message}`);
    throw err;
  }
});

ipcMain.handle('detect-drift', async (_e, localCode: string, config: EnvConfig) => {
  log(`Checking for drift against ${config.cloudProvider}...`);
  try {
    const result = await detectDrift(localCode, config);
    log(result.hasDrift ? '⚠️  Drift detected' : '✅ No drift');
    return result;
  } catch (err: any) {
    log(`❌ Drift check failed: ${err.message}`);
    throw err;
  }
});

// ─── Rollback with healthcheck ─────────────────────────────────────────────
ipcMain.handle('rollback-with-healthcheck', async (_e, record: DeployRecord, config: EnvConfig) => {
  log(`Rolling back to deployment from ${new Date(record.timestamp).toLocaleString()}...`);
  try {
    const result = await rollbackDeploy(record, config, log);
    log(`✅ Rollback complete: ${result.url}`);

    if (result.url) {
      log('Running post-rollback healthcheck...');
      const health = await healthcheckDeploy(result.url, config.cloudProvider);
      if (health.ok) {
        log(`✅ Healthcheck passed (${health.latencyMs}ms)`);
      } else {
        log(`⚠️  Healthcheck failed: ${health.error ?? 'unknown error'}`);
      }
      return { ...result, health };
    }

    return result;
  } catch (err: any) {
    log(`❌ Rollback failed: ${err.message}`);
    throw err;
  }
});

// ─── AI code generation ───────────────────────────────────────────────────
ipcMain.handle('ai-generate', async (_e, prompt: string, apiKey: string) => {
  return generateWorkerFromPrompt(prompt, apiKey);
});

// ─── Open external links ──────────────────────────────────────────────────
ipcMain.handle('open-external', async (_e, url: string) => {
  await shell.openExternal(url);
});

// ─── Telemetry ────────────────────────────────────────────────────────────
ipcMain.handle('get-telemetry-level', async () => {
  return getTelemetryLevel();
});

ipcMain.handle('set-telemetry-level', async (_e, level: TelemetryLevel) => {
  await setTelemetryLevel(level);
});

// ─── Cloudflare log tail ──────────────────────────────────────────────────
// Active tail WebSockets keyed by tailId
const activeTails = new Map<string, WebSocket>();

ipcMain.handle('cf-tail-start', async (_e, config: EnvConfig) => {
  const { cfApiToken, cfAccountId, cfScriptName } = config;
  if (!cfApiToken || !cfAccountId || !cfScriptName) {
    throw new Error('Cloudflare credentials required for log tail');
  }

  // Create a tail session via the Cloudflare API
  const res = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${cfAccountId}/workers/scripts/${cfScriptName}/tails`,
    { method: 'POST', headers: { Authorization: `Bearer ${cfApiToken}`, 'Content-Type': 'application/json' }, body: '{}' }
  );
  const json: any = await res.json();
  if (!json.success) throw new Error(`Tail failed: ${json.errors?.[0]?.message ?? 'unknown'}`);

  const { id: tailId, url: tailWsUrl } = json.result;

  // Connect WebSocket and stream logs back to renderer
  const { default: WebSocket } = await import('ws' as any).catch(() => ({ default: (global as any).WebSocket }));
  const ws = new WebSocket(tailWsUrl, ['trace-v1'], {
    headers: { Authorization: `Bearer ${cfApiToken}` },
  });

  ws.on('message', (data: any) => {
    try {
      const msg = JSON.parse(data.toString());
      if (msg.logs) {
        for (const entry of msg.logs) {
          mainWindow?.webContents.send('cf-tail-log', {
            tailId,
            message: entry.message ?? JSON.stringify(entry),
            level: entry.level ?? 'log',
            timestamp: new Date(msg.eventTimestamp ?? Date.now()).toISOString(),
          });
        }
      }
    } catch {}
  });

  ws.on('error', () => activeTails.delete(tailId));
  ws.on('close', () => activeTails.delete(tailId));

  activeTails.set(tailId, ws as any);
  return { tailId };
});

ipcMain.handle('cf-tail-stop', async (_e, tailId: string, config: EnvConfig) => {
  const ws = activeTails.get(tailId);
  if (ws) { (ws as any).close(); activeTails.delete(tailId); }

  const { cfApiToken, cfAccountId, cfScriptName } = config;
  if (cfApiToken && cfAccountId && cfScriptName) {
    await fetch(
      `https://api.cloudflare.com/client/v4/accounts/${cfAccountId}/workers/scripts/${cfScriptName}/tails/${tailId}`,
      { method: 'DELETE', headers: { Authorization: `Bearer ${cfApiToken}` } }
    ).catch(() => {});
  }
});
